version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - cd infra/lambda_base_layer
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r ../layer.zip .
      - cd ../../..
      - zip -gr deployment_package.zip .
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name InfraStack-ApiFunctionCE271BD4-QJGmuSx5vNPN --zip-file fileb://deployment_package.zip
      - echo "DONE!!"