version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - cd infra/lambda_base_layer
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping base layer..."
      - cd lib
      - zip -r ../../../layer.zip .
      - cd ../../..
      - echo "Zipping function code..."
      - cd python-backend
      - zip -r ../function.zip .
      - cd ..
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name InfraStack-ApiFunctionCE271BD4-QJGmuSx5vNPN --zip-file fileb://function.zip
      - echo "Updating lambda Layer..."
      - aws lambda publish-layer-version --layer-name arn:aws:lambda:us-east-2:055086161576:layer:BaseLayer786B35E5 --zip-file fileb://layer.zip
      - echo "DONE!!"